apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
            - name: ConnectionStrings__ASPNETDbConnection
              value: Server=sql-server,1433;Database=ASPNETDb;User Id=sa;Password=StrongPassword@123;Max Pool Size=100;Encrypt=false
            - name: ConnectionStrings__QueueDbConnection
              value: Server=sql-server,1433;Database=QueueDb;User Id=sa;Password=StrongPassword@123;Max Pool Size=100;Encrypt=false
          image: client:latest-k8s
          name: client
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
