apiVersion: v1
kind: Service
metadata:
  name: cronjobmanager
  labels:
    app: cronjobmanager
spec:
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30050  # NodePort must be between 30000-32767
  selector:
    app: cronjobmanager
