apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronjobmanager
  template:
    metadata:
      labels:
        app: cronjobmanager
    spec:
      containers:
      - name: cronjobmanager
        image: cronjobmanager:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://+:5000
        - name: ConnectionStrings__CronJobManagerDbConnection
          value: Server=host.docker.internal,1433;Database=CronJobManagerDb;User Id=sa;Password=StrongPassword123;Max Pool Size=100;Encrypt=false
