apiVersion: v1
kind: Service
metadata:
  name: cronjobmanager
spec:
  type: NodePort
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30500  # NodePort must be between 30000-32767
  selector:
    app: cronjobmanager
