apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cronjobmanager
  name: cronjobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cronjobmanager
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cronjobmanager
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: ConnectionStrings__CronJobManagerDbConnection
              value: Server=host.docker.internal,1433;Database=CronJobManagerDb;User Id=sa;Password=StrongPassword123;Max Pool Size=100;Encrypt=false
          image: cronjobmanager
          name: cronjobmanager
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
