apiVersion: v1
kind: Service
metadata:
  labels:
    app: cronjobmanager
  name: cronjobmanager
spec:
  type: NodePort  # Add this line if you need external access  
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30050
  selector:
    app: cronjobmanager
