apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cronjobmanager
  name: cronjobmanager
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: cronjobmanager
