apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081  # NodePort must be between 30000-32767
  selector:
    app: server
