apiVersion: v1
kind: Service
metadata:
  name: sql-server
spec:
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30000  # Specify a port between 30000-32767
  type: NodePort
